[package]
name = "rumqttc-ng"
version = "0.90.0"
edition.workspace = true
repository.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
tokio = { version = "1", features = ["full"] }
base = { path = "../base" }
